/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-background": "#1c1b1b",
        "error": "#ba1a1a",
        "surface-container-high": "#ebe7e7",
        "on-surface": "#1c1b1b",
        "tertiary": "#a43c12",
        "surface-container-lowest": "#ffffff",
        "primary-container": "#00d1a0",
        "tertiary-container": "#ffa180",
        "surface-tint": "#006c51",
        "primary-fixed-dim": "#2ee0ad",
        "inverse-surface": "#313030",
        "tertiary-fixed": "#ffdbcf",
        "surface-container-highest": "#e5e2e1",
        "on-tertiary-container": "#862900",
        "surface-container": "#f0edec",
        "background": "#fcf9f8",
        "on-primary-fixed-variant": "#00513c",
        "surface-variant": "#e5e2e1",
        "surface-container-low": "#f6f3f2",
        "on-secondary-fixed": "#1b1c1c",
        "on-primary-container": "#00543e",
        "surface-bright": "#fcf9f8",
        "primary": "#006c51",
        "secondary": "#5f5e5e",
        "inverse-primary": "#2ee0ad",
        "error-container": "#ffdad6",
        "on-primary": "#ffffff",
        "primary-fixed": "#58fdc8",
        "surface": "#fcf9f8",
        "on-surface-variant": "#3b4a43",
        "secondary-fixed-dim": "#c8c6c6",
        "inverse-on-surface": "#f3f0ef",
        "on-error": "#ffffff",
        "outline-variant": "#bacac1",
        "on-secondary-fixed-variant": "#474747",
        "surface-dim": "#dcd9d9",
        "on-tertiary-fixed-variant": "#822800",
        "on-secondary": "#ffffff",
        "secondary-fixed": "#e4e2e1",
        "on-secondary-container": "#656464",
        "outline": "#6b7b73",
        "on-tertiary-fixed": "#380c00",
        "on-tertiary": "#ffffff",
        "on-error-container": "#93000a",
        "on-primary-fixed": "#002116",
        "tertiary-fixed-dim": "#ffb59c",
        "secondary-container": "#e4e2e1"
      },
      fontFamily: {
        headline: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
}
